### ISSUE TITLE
third subpage is not crawled

### ISSUE THREAD

**Issue by kojambo** [kojambo/repo1#1]
I checked the completeness of the results and found that prices from the third (sub)page are missing. The next_page code from the scrapy tutorial [1] says it creates a loop, it does not seem to work or third page result are overwritten or somehow not included in the extract.

```
    next_page = response.css("div.pagination > div.inner > a::attr('href')")
    if next_page:
        url = response.urljoin(next_page[0].extract())
        yield scrapy.Request(url, self.parse_dir_contents)
```

[1] http://doc.scrapy.org/en/latest/intro/tutorial.html#following-links

**Comment by JensAldinger** [comment]
next_page was not included in response.css, therefore it was not clear what link to take
